Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
